//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionPersonalTrainingProject.usercontrols.VVT {
    
    
    public partial class WeightsSessionsTab {
        
        /// <summary>
        /// WeightsSessTab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl WeightsSessTab;
        
        /// <summary>
        /// WeightsHis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisionPersonalTrainingProject.usercontrols.VVT.WeightsSessionsHistory WeightsHis;
        
        /// <summary>
        /// createWeightsProg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisionPersonalTrainingProject.usercontrols.VVT.VVT_Initial_Steps.ExercisePlanner createWeightsProg;
        
        /// <summary>
        /// currWeihgts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VisionPersonalTrainingProject.usercontrols.VVT.WeightSessions currWeihgts;
        
        /// <summary>
        /// weightsSessScript control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal weightsSessScript;
    }
}
