//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace VisionPersonalTrainingProject.VOSWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private AuthenticationHeader authenticationHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetUserRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserMembersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserMemberEmailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberLoginAvailabilityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberGoalsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberTrainingOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberWeightHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberPTSessionHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMemberPTSessionDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMemberPasswordAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitEventRegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitEnquiryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWhatsOnOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPartnersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::VisionPersonalTrainingProject.Properties.Settings.Default.VisionPersonalTrainingProject_VOSWebService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthenticationHeader AuthenticationHeaderValue {
            get {
                return this.authenticationHeaderValueField;
            }
            set {
                this.authenticationHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event GetUserRoleCompletedEventHandler GetUserRoleCompleted;
        
        /// <remarks/>
        public event GetUserMembersCompletedEventHandler GetUserMembersCompleted;
        
        /// <remarks/>
        public event GetUserMemberEmailsCompletedEventHandler GetUserMemberEmailsCompleted;
        
        /// <remarks/>
        public event GetMemberLoginCompletedEventHandler GetMemberLoginCompleted;
        
        /// <remarks/>
        public event GetMemberLoginAvailabilityCompletedEventHandler GetMemberLoginAvailabilityCompleted;
        
        /// <remarks/>
        public event GetMemberGoalsCompletedEventHandler GetMemberGoalsCompleted;
        
        /// <remarks/>
        public event GetMemberPasswordCompletedEventHandler GetMemberPasswordCompleted;
        
        /// <remarks/>
        public event GetMemberTrainingCompletedEventHandler GetMemberTrainingCompleted;
        
        /// <remarks/>
        public event GetMemberWeightHistoryCompletedEventHandler GetMemberWeightHistoryCompleted;
        
        /// <remarks/>
        public event GetMemberPTSessionHistoryCompletedEventHandler GetMemberPTSessionHistoryCompleted;
        
        /// <remarks/>
        public event GetMemberPTSessionDatesCompletedEventHandler GetMemberPTSessionDatesCompleted;
        
        /// <remarks/>
        public event UpdateMemberPasswordAccountCompletedEventHandler UpdateMemberPasswordAccountCompleted;
        
        /// <remarks/>
        public event SubmitEventCompletedEventHandler SubmitEventCompleted;
        
        /// <remarks/>
        public event SubmitEventRegisterCompletedEventHandler SubmitEventRegisterCompleted;
        
        /// <remarks/>
        public event SubmitEnquiryCompletedEventHandler SubmitEnquiryCompleted;
        
        /// <remarks/>
        public event GetWhatsOnCompletedEventHandler GetWhatsOnCompleted;
        
        /// <remarks/>
        public event GetPartnersCompletedEventHandler GetPartnersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserRole", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserRole GetUserRole(string cUserName, ref string cPassword) {
            object[] results = this.Invoke("GetUserRole", new object[] {
                        cUserName,
                        cPassword});
            cPassword = ((string)(results[1]));
            return ((UserRole)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserRoleAsync(string cUserName, string cPassword) {
            this.GetUserRoleAsync(cUserName, cPassword, null);
        }
        
        /// <remarks/>
        public void GetUserRoleAsync(string cUserName, string cPassword, object userState) {
            if ((this.GetUserRoleOperationCompleted == null)) {
                this.GetUserRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserRoleOperationCompleted);
            }
            this.InvokeAsync("GetUserRole", new object[] {
                        cUserName,
                        cPassword}, this.GetUserRoleOperationCompleted, userState);
        }
        
        private void OnGetUserRoleOperationCompleted(object arg) {
            if ((this.GetUserRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserRoleCompleted(this, new GetUserRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserMembers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserMembers(int iUser) {
            object[] results = this.Invoke("GetUserMembers", new object[] {
                        iUser});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserMembersAsync(int iUser) {
            this.GetUserMembersAsync(iUser, null);
        }
        
        /// <remarks/>
        public void GetUserMembersAsync(int iUser, object userState) {
            if ((this.GetUserMembersOperationCompleted == null)) {
                this.GetUserMembersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserMembersOperationCompleted);
            }
            this.InvokeAsync("GetUserMembers", new object[] {
                        iUser}, this.GetUserMembersOperationCompleted, userState);
        }
        
        private void OnGetUserMembersOperationCompleted(object arg) {
            if ((this.GetUserMembersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserMembersCompleted(this, new GetUserMembersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserMemberEmails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetUserMemberEmails(int iUser, int iType) {
            object[] results = this.Invoke("GetUserMemberEmails", new object[] {
                        iUser,
                        iType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserMemberEmailsAsync(int iUser, int iType) {
            this.GetUserMemberEmailsAsync(iUser, iType, null);
        }
        
        /// <remarks/>
        public void GetUserMemberEmailsAsync(int iUser, int iType, object userState) {
            if ((this.GetUserMemberEmailsOperationCompleted == null)) {
                this.GetUserMemberEmailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserMemberEmailsOperationCompleted);
            }
            this.InvokeAsync("GetUserMemberEmails", new object[] {
                        iUser,
                        iType}, this.GetUserMemberEmailsOperationCompleted, userState);
        }
        
        private void OnGetUserMemberEmailsOperationCompleted(object arg) {
            if ((this.GetUserMemberEmailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserMemberEmailsCompleted(this, new GetUserMemberEmailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MemberLogin GetMemberLogin(string cUserName, ref string cPassword) {
            object[] results = this.Invoke("GetMemberLogin", new object[] {
                        cUserName,
                        cPassword});
            cPassword = ((string)(results[1]));
            return ((MemberLogin)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberLoginAsync(string cUserName, string cPassword) {
            this.GetMemberLoginAsync(cUserName, cPassword, null);
        }
        
        /// <remarks/>
        public void GetMemberLoginAsync(string cUserName, string cPassword, object userState) {
            if ((this.GetMemberLoginOperationCompleted == null)) {
                this.GetMemberLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberLoginOperationCompleted);
            }
            this.InvokeAsync("GetMemberLogin", new object[] {
                        cUserName,
                        cPassword}, this.GetMemberLoginOperationCompleted, userState);
        }
        
        private void OnGetMemberLoginOperationCompleted(object arg) {
            if ((this.GetMemberLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberLoginCompleted(this, new GetMemberLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberLoginAvailability", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MemberLoginAvailability GetMemberLoginAvailability(string cLogin, int iType) {
            object[] results = this.Invoke("GetMemberLoginAvailability", new object[] {
                        cLogin,
                        iType});
            return ((MemberLoginAvailability)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberLoginAvailabilityAsync(string cLogin, int iType) {
            this.GetMemberLoginAvailabilityAsync(cLogin, iType, null);
        }
        
        /// <remarks/>
        public void GetMemberLoginAvailabilityAsync(string cLogin, int iType, object userState) {
            if ((this.GetMemberLoginAvailabilityOperationCompleted == null)) {
                this.GetMemberLoginAvailabilityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberLoginAvailabilityOperationCompleted);
            }
            this.InvokeAsync("GetMemberLoginAvailability", new object[] {
                        cLogin,
                        iType}, this.GetMemberLoginAvailabilityOperationCompleted, userState);
        }
        
        private void OnGetMemberLoginAvailabilityOperationCompleted(object arg) {
            if ((this.GetMemberLoginAvailabilityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberLoginAvailabilityCompleted(this, new GetMemberLoginAvailabilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberGoals", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MemberGoals GetMemberGoals(int iMemberNo) {
            object[] results = this.Invoke("GetMemberGoals", new object[] {
                        iMemberNo});
            return ((MemberGoals)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberGoalsAsync(int iMemberNo) {
            this.GetMemberGoalsAsync(iMemberNo, null);
        }
        
        /// <remarks/>
        public void GetMemberGoalsAsync(int iMemberNo, object userState) {
            if ((this.GetMemberGoalsOperationCompleted == null)) {
                this.GetMemberGoalsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberGoalsOperationCompleted);
            }
            this.InvokeAsync("GetMemberGoals", new object[] {
                        iMemberNo}, this.GetMemberGoalsOperationCompleted, userState);
        }
        
        private void OnGetMemberGoalsOperationCompleted(object arg) {
            if ((this.GetMemberGoalsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberGoalsCompleted(this, new GetMemberGoalsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberPassword(string cEmail, string cUserName) {
            object[] results = this.Invoke("GetMemberPassword", new object[] {
                        cEmail,
                        cUserName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberPasswordAsync(string cEmail, string cUserName) {
            this.GetMemberPasswordAsync(cEmail, cUserName, null);
        }
        
        /// <remarks/>
        public void GetMemberPasswordAsync(string cEmail, string cUserName, object userState) {
            if ((this.GetMemberPasswordOperationCompleted == null)) {
                this.GetMemberPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberPasswordOperationCompleted);
            }
            this.InvokeAsync("GetMemberPassword", new object[] {
                        cEmail,
                        cUserName}, this.GetMemberPasswordOperationCompleted, userState);
        }
        
        private void OnGetMemberPasswordOperationCompleted(object arg) {
            if ((this.GetMemberPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberPasswordCompleted(this, new GetMemberPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberTraining", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberTraining(int iMemberNo) {
            object[] results = this.Invoke("GetMemberTraining", new object[] {
                        iMemberNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberTrainingAsync(int iMemberNo) {
            this.GetMemberTrainingAsync(iMemberNo, null);
        }
        
        /// <remarks/>
        public void GetMemberTrainingAsync(int iMemberNo, object userState) {
            if ((this.GetMemberTrainingOperationCompleted == null)) {
                this.GetMemberTrainingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberTrainingOperationCompleted);
            }
            this.InvokeAsync("GetMemberTraining", new object[] {
                        iMemberNo}, this.GetMemberTrainingOperationCompleted, userState);
        }
        
        private void OnGetMemberTrainingOperationCompleted(object arg) {
            if ((this.GetMemberTrainingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberTrainingCompleted(this, new GetMemberTrainingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberWeightHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberWeightHistory(int iMemberNo) {
            object[] results = this.Invoke("GetMemberWeightHistory", new object[] {
                        iMemberNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberWeightHistoryAsync(int iMemberNo) {
            this.GetMemberWeightHistoryAsync(iMemberNo, null);
        }
        
        /// <remarks/>
        public void GetMemberWeightHistoryAsync(int iMemberNo, object userState) {
            if ((this.GetMemberWeightHistoryOperationCompleted == null)) {
                this.GetMemberWeightHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberWeightHistoryOperationCompleted);
            }
            this.InvokeAsync("GetMemberWeightHistory", new object[] {
                        iMemberNo}, this.GetMemberWeightHistoryOperationCompleted, userState);
        }
        
        private void OnGetMemberWeightHistoryOperationCompleted(object arg) {
            if ((this.GetMemberWeightHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberWeightHistoryCompleted(this, new GetMemberWeightHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberPTSessionHistory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberPTSessionHistory(int iMemberNo, string cPTType, string cPTDate) {
            object[] results = this.Invoke("GetMemberPTSessionHistory", new object[] {
                        iMemberNo,
                        cPTType,
                        cPTDate});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberPTSessionHistoryAsync(int iMemberNo, string cPTType, string cPTDate) {
            this.GetMemberPTSessionHistoryAsync(iMemberNo, cPTType, cPTDate, null);
        }
        
        /// <remarks/>
        public void GetMemberPTSessionHistoryAsync(int iMemberNo, string cPTType, string cPTDate, object userState) {
            if ((this.GetMemberPTSessionHistoryOperationCompleted == null)) {
                this.GetMemberPTSessionHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberPTSessionHistoryOperationCompleted);
            }
            this.InvokeAsync("GetMemberPTSessionHistory", new object[] {
                        iMemberNo,
                        cPTType,
                        cPTDate}, this.GetMemberPTSessionHistoryOperationCompleted, userState);
        }
        
        private void OnGetMemberPTSessionHistoryOperationCompleted(object arg) {
            if ((this.GetMemberPTSessionHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberPTSessionHistoryCompleted(this, new GetMemberPTSessionHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMemberPTSessionDates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMemberPTSessionDates(int iMemberNo, string cPTType) {
            object[] results = this.Invoke("GetMemberPTSessionDates", new object[] {
                        iMemberNo,
                        cPTType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMemberPTSessionDatesAsync(int iMemberNo, string cPTType) {
            this.GetMemberPTSessionDatesAsync(iMemberNo, cPTType, null);
        }
        
        /// <remarks/>
        public void GetMemberPTSessionDatesAsync(int iMemberNo, string cPTType, object userState) {
            if ((this.GetMemberPTSessionDatesOperationCompleted == null)) {
                this.GetMemberPTSessionDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMemberPTSessionDatesOperationCompleted);
            }
            this.InvokeAsync("GetMemberPTSessionDates", new object[] {
                        iMemberNo,
                        cPTType}, this.GetMemberPTSessionDatesOperationCompleted, userState);
        }
        
        private void OnGetMemberPTSessionDatesOperationCompleted(object arg) {
            if ((this.GetMemberPTSessionDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMemberPTSessionDatesCompleted(this, new GetMemberPTSessionDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateMemberPasswordAccount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public MemberPassword UpdateMemberPasswordAccount(int iMemberNo, string cPasswordOld, ref string cPasswordNew) {
            object[] results = this.Invoke("UpdateMemberPasswordAccount", new object[] {
                        iMemberNo,
                        cPasswordOld,
                        cPasswordNew});
            cPasswordNew = ((string)(results[1]));
            return ((MemberPassword)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMemberPasswordAccountAsync(int iMemberNo, string cPasswordOld, string cPasswordNew) {
            this.UpdateMemberPasswordAccountAsync(iMemberNo, cPasswordOld, cPasswordNew, null);
        }
        
        /// <remarks/>
        public void UpdateMemberPasswordAccountAsync(int iMemberNo, string cPasswordOld, string cPasswordNew, object userState) {
            if ((this.UpdateMemberPasswordAccountOperationCompleted == null)) {
                this.UpdateMemberPasswordAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMemberPasswordAccountOperationCompleted);
            }
            this.InvokeAsync("UpdateMemberPasswordAccount", new object[] {
                        iMemberNo,
                        cPasswordOld,
                        cPasswordNew}, this.UpdateMemberPasswordAccountOperationCompleted, userState);
        }
        
        private void OnUpdateMemberPasswordAccountOperationCompleted(object arg) {
            if ((this.UpdateMemberPasswordAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMemberPasswordAccountCompleted(this, new UpdateMemberPasswordAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public stEventUpdate SubmitEvent(stEventUpdate oEvent) {
            object[] results = this.Invoke("SubmitEvent", new object[] {
                        oEvent});
            return ((stEventUpdate)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitEventAsync(stEventUpdate oEvent) {
            this.SubmitEventAsync(oEvent, null);
        }
        
        /// <remarks/>
        public void SubmitEventAsync(stEventUpdate oEvent, object userState) {
            if ((this.SubmitEventOperationCompleted == null)) {
                this.SubmitEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitEventOperationCompleted);
            }
            this.InvokeAsync("SubmitEvent", new object[] {
                        oEvent}, this.SubmitEventOperationCompleted, userState);
        }
        
        private void OnSubmitEventOperationCompleted(object arg) {
            if ((this.SubmitEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitEventCompleted(this, new SubmitEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitEventRegister", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public stEventUpdate SubmitEventRegister(stEventUpdate oEvent) {
            object[] results = this.Invoke("SubmitEventRegister", new object[] {
                        oEvent});
            return ((stEventUpdate)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitEventRegisterAsync(stEventUpdate oEvent) {
            this.SubmitEventRegisterAsync(oEvent, null);
        }
        
        /// <remarks/>
        public void SubmitEventRegisterAsync(stEventUpdate oEvent, object userState) {
            if ((this.SubmitEventRegisterOperationCompleted == null)) {
                this.SubmitEventRegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitEventRegisterOperationCompleted);
            }
            this.InvokeAsync("SubmitEventRegister", new object[] {
                        oEvent}, this.SubmitEventRegisterOperationCompleted, userState);
        }
        
        private void OnSubmitEventRegisterOperationCompleted(object arg) {
            if ((this.SubmitEventRegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitEventRegisterCompleted(this, new SubmitEventRegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitEnquiry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public stEnquiryUpdate SubmitEnquiry(stEnquiryUpdate oEnquiry) {
            object[] results = this.Invoke("SubmitEnquiry", new object[] {
                        oEnquiry});
            return ((stEnquiryUpdate)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitEnquiryAsync(stEnquiryUpdate oEnquiry) {
            this.SubmitEnquiryAsync(oEnquiry, null);
        }
        
        /// <remarks/>
        public void SubmitEnquiryAsync(stEnquiryUpdate oEnquiry, object userState) {
            if ((this.SubmitEnquiryOperationCompleted == null)) {
                this.SubmitEnquiryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitEnquiryOperationCompleted);
            }
            this.InvokeAsync("SubmitEnquiry", new object[] {
                        oEnquiry}, this.SubmitEnquiryOperationCompleted, userState);
        }
        
        private void OnSubmitEnquiryOperationCompleted(object arg) {
            if ((this.SubmitEnquiryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitEnquiryCompleted(this, new SubmitEnquiryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWhatsOn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWhatsOn(int iStudioID, int iWhatsOn) {
            object[] results = this.Invoke("GetWhatsOn", new object[] {
                        iStudioID,
                        iWhatsOn});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWhatsOnAsync(int iStudioID, int iWhatsOn) {
            this.GetWhatsOnAsync(iStudioID, iWhatsOn, null);
        }
        
        /// <remarks/>
        public void GetWhatsOnAsync(int iStudioID, int iWhatsOn, object userState) {
            if ((this.GetWhatsOnOperationCompleted == null)) {
                this.GetWhatsOnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWhatsOnOperationCompleted);
            }
            this.InvokeAsync("GetWhatsOn", new object[] {
                        iStudioID,
                        iWhatsOn}, this.GetWhatsOnOperationCompleted, userState);
        }
        
        private void OnGetWhatsOnOperationCompleted(object arg) {
            if ((this.GetWhatsOnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWhatsOnCompleted(this, new GetWhatsOnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPartners", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPartners(int iStudioID) {
            object[] results = this.Invoke("GetPartners", new object[] {
                        iStudioID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPartnersAsync(int iStudioID) {
            this.GetPartnersAsync(iStudioID, null);
        }
        
        /// <remarks/>
        public void GetPartnersAsync(int iStudioID, object userState) {
            if ((this.GetPartnersOperationCompleted == null)) {
                this.GetPartnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPartnersOperationCompleted);
            }
            this.InvokeAsync("GetPartners", new object[] {
                        iStudioID}, this.GetPartnersOperationCompleted, userState);
        }
        
        private void OnGetPartnersOperationCompleted(object arg) {
            if ((this.GetPartnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPartnersCompleted(this, new GetPartnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class AuthenticationHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class stEnquiryUpdate {
        
        private int enquiryIDField;
        
        private int studioIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string mobilePhoneField;
        
        private string daytimePhoneField;
        
        private string emailField;
        
        private string noteField;
        
        private int sourceField;
        
        private int lightBoxIDField;
        
        /// <remarks/>
        public int EnquiryID {
            get {
                return this.enquiryIDField;
            }
            set {
                this.enquiryIDField = value;
            }
        }
        
        /// <remarks/>
        public int StudioID {
            get {
                return this.studioIDField;
            }
            set {
                this.studioIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string DaytimePhone {
            get {
                return this.daytimePhoneField;
            }
            set {
                this.daytimePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public int LightBoxID {
            get {
                return this.lightBoxIDField;
            }
            set {
                this.lightBoxIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class stEventUpdate {
        
        private int eventIDField;
        
        private int registerIDField;
        
        private int studioIDField;
        
        private int memberNoField;
        
        private int categoryField;
        
        private System.DateTime eventDateField;
        
        private System.DateTime eventTimeField;
        
        private string eventTitleField;
        
        private string informationField;
        
        private string placeField;
        
        private string meetingPlaceField;
        
        private int sourceField;
        
        /// <remarks/>
        public int EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        public int RegisterID {
            get {
                return this.registerIDField;
            }
            set {
                this.registerIDField = value;
            }
        }
        
        /// <remarks/>
        public int StudioID {
            get {
                return this.studioIDField;
            }
            set {
                this.studioIDField = value;
            }
        }
        
        /// <remarks/>
        public int MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        public int Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EventTime {
            get {
                return this.eventTimeField;
            }
            set {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        public string EventTitle {
            get {
                return this.eventTitleField;
            }
            set {
                this.eventTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Information {
            get {
                return this.informationField;
            }
            set {
                this.informationField = value;
            }
        }
        
        /// <remarks/>
        public string Place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        public string MeetingPlace {
            get {
                return this.meetingPlaceField;
            }
            set {
                this.meetingPlaceField = value;
            }
        }
        
        /// <remarks/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberPassword {
        
        private int updateField;
        
        /// <remarks/>
        public int Update {
            get {
                return this.updateField;
            }
            set {
                this.updateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberGoals {
        
        private int memberNoField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string streetAddressField;
        
        private string cityField;
        
        private string stateField;
        
        private string postcodeField;
        
        private string countryField;
        
        private string daytimePhoneField;
        
        private string mobilePhoneField;
        
        private string emailField;
        
        private string myStudioField;
        
        private int myStudioIDField;
        
        private string myTrainerField;
        
        private int myTrainerIDField;
        
        private string myTrainerContactField;
        
        private string myTrainerEmailField;
        
        private double cHOField;
        
        private double pTNField;
        
        private double fATField;
        
        private string goalField;
        
        private string programField;
        
        private System.DateTime gSDateField;
        
        private System.DateTime nextGSField;
        
        private string goalWtField;
        
        private string nowWtField;
        
        private System.DateTime startDateField;
        
        private string startWtField;
        
        private string progressWtField;
        
        private string cWRatioField;
        
        private string cardioField;
        
        private string weightsField;
        
        private string cardioLMField;
        
        private string cardioHardField;
        
        private string acceleratorField;
        
        private string weeklyWtField;
        
        private string weeklyGoalField;
        
        /// <remarks/>
        public int MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string StreetAddress {
            get {
                return this.streetAddressField;
            }
            set {
                this.streetAddressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Postcode {
            get {
                return this.postcodeField;
            }
            set {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string DaytimePhone {
            get {
                return this.daytimePhoneField;
            }
            set {
                this.daytimePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string MyStudio {
            get {
                return this.myStudioField;
            }
            set {
                this.myStudioField = value;
            }
        }
        
        /// <remarks/>
        public int MyStudioID {
            get {
                return this.myStudioIDField;
            }
            set {
                this.myStudioIDField = value;
            }
        }
        
        /// <remarks/>
        public string MyTrainer {
            get {
                return this.myTrainerField;
            }
            set {
                this.myTrainerField = value;
            }
        }
        
        /// <remarks/>
        public int MyTrainerID {
            get {
                return this.myTrainerIDField;
            }
            set {
                this.myTrainerIDField = value;
            }
        }
        
        /// <remarks/>
        public string MyTrainerContact {
            get {
                return this.myTrainerContactField;
            }
            set {
                this.myTrainerContactField = value;
            }
        }
        
        /// <remarks/>
        public string MyTrainerEmail {
            get {
                return this.myTrainerEmailField;
            }
            set {
                this.myTrainerEmailField = value;
            }
        }
        
        /// <remarks/>
        public double CHO {
            get {
                return this.cHOField;
            }
            set {
                this.cHOField = value;
            }
        }
        
        /// <remarks/>
        public double PTN {
            get {
                return this.pTNField;
            }
            set {
                this.pTNField = value;
            }
        }
        
        /// <remarks/>
        public double FAT {
            get {
                return this.fATField;
            }
            set {
                this.fATField = value;
            }
        }
        
        /// <remarks/>
        public string Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        public string Program {
            get {
                return this.programField;
            }
            set {
                this.programField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime GSDate {
            get {
                return this.gSDateField;
            }
            set {
                this.gSDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime NextGS {
            get {
                return this.nextGSField;
            }
            set {
                this.nextGSField = value;
            }
        }
        
        /// <remarks/>
        public string GoalWt {
            get {
                return this.goalWtField;
            }
            set {
                this.goalWtField = value;
            }
        }
        
        /// <remarks/>
        public string NowWt {
            get {
                return this.nowWtField;
            }
            set {
                this.nowWtField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        public string StartWt {
            get {
                return this.startWtField;
            }
            set {
                this.startWtField = value;
            }
        }
        
        /// <remarks/>
        public string ProgressWt {
            get {
                return this.progressWtField;
            }
            set {
                this.progressWtField = value;
            }
        }
        
        /// <remarks/>
        public string CWRatio {
            get {
                return this.cWRatioField;
            }
            set {
                this.cWRatioField = value;
            }
        }
        
        /// <remarks/>
        public string Cardio {
            get {
                return this.cardioField;
            }
            set {
                this.cardioField = value;
            }
        }
        
        /// <remarks/>
        public string Weights {
            get {
                return this.weightsField;
            }
            set {
                this.weightsField = value;
            }
        }
        
        /// <remarks/>
        public string CardioLM {
            get {
                return this.cardioLMField;
            }
            set {
                this.cardioLMField = value;
            }
        }
        
        /// <remarks/>
        public string CardioHard {
            get {
                return this.cardioHardField;
            }
            set {
                this.cardioHardField = value;
            }
        }
        
        /// <remarks/>
        public string Accelerator {
            get {
                return this.acceleratorField;
            }
            set {
                this.acceleratorField = value;
            }
        }
        
        /// <remarks/>
        public string WeeklyWt {
            get {
                return this.weeklyWtField;
            }
            set {
                this.weeklyWtField = value;
            }
        }
        
        /// <remarks/>
        public string WeeklyGoal {
            get {
                return this.weeklyGoalField;
            }
            set {
                this.weeklyGoalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberLoginAvailability {
        
        private bool loginAvailableField;
        
        /// <remarks/>
        public bool LoginAvailable {
            get {
                return this.loginAvailableField;
            }
            set {
                this.loginAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MemberLogin {
        
        private int loginField;
        
        private int memberNoField;
        
        private string memberField;
        
        private int studioIDField;
        
        private string studioField;
        
        private string cVUserNameField;
        
        private string cVPasswordField;
        
        private int trainerIDField;
        
        private int memberTypeField;
        
        /// <remarks/>
        public int Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public int MemberNo {
            get {
                return this.memberNoField;
            }
            set {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        public string Member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        public int StudioID {
            get {
                return this.studioIDField;
            }
            set {
                this.studioIDField = value;
            }
        }
        
        /// <remarks/>
        public string Studio {
            get {
                return this.studioField;
            }
            set {
                this.studioField = value;
            }
        }
        
        /// <remarks/>
        public string CVUserName {
            get {
                return this.cVUserNameField;
            }
            set {
                this.cVUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string CVPassword {
            get {
                return this.cVPasswordField;
            }
            set {
                this.cVPasswordField = value;
            }
        }
        
        /// <remarks/>
        public int TrainerID {
            get {
                return this.trainerIDField;
            }
            set {
                this.trainerIDField = value;
            }
        }
        
        /// <remarks/>
        public int MemberType {
            get {
                return this.memberTypeField;
            }
            set {
                this.memberTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserRole {
        
        private int roleIDField;
        
        private int userIDField;
        
        private string userField;
        
        private int studioIDField;
        
        private string studioField;
        
        private int levelIDField;
        
        private string emailField;
        
        /// <remarks/>
        public int RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public int StudioID {
            get {
                return this.studioIDField;
            }
            set {
                this.studioIDField = value;
            }
        }
        
        /// <remarks/>
        public string Studio {
            get {
                return this.studioField;
            }
            set {
                this.studioField = value;
            }
        }
        
        /// <remarks/>
        public int LevelID {
            get {
                return this.levelIDField;
            }
            set {
                this.levelIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserRoleCompletedEventHandler(object sender, GetUserRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserRole Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserRole)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string cPassword {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserMembersCompletedEventHandler(object sender, GetUserMembersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserMembersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserMembersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetUserMemberEmailsCompletedEventHandler(object sender, GetUserMemberEmailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserMemberEmailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserMemberEmailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberLoginCompletedEventHandler(object sender, GetMemberLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MemberLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MemberLogin)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string cPassword {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberLoginAvailabilityCompletedEventHandler(object sender, GetMemberLoginAvailabilityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberLoginAvailabilityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberLoginAvailabilityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MemberLoginAvailability Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MemberLoginAvailability)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberGoalsCompletedEventHandler(object sender, GetMemberGoalsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberGoalsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberGoalsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MemberGoals Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MemberGoals)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberPasswordCompletedEventHandler(object sender, GetMemberPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberTrainingCompletedEventHandler(object sender, GetMemberTrainingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberTrainingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberTrainingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberWeightHistoryCompletedEventHandler(object sender, GetMemberWeightHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberWeightHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberWeightHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberPTSessionHistoryCompletedEventHandler(object sender, GetMemberPTSessionHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberPTSessionHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberPTSessionHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMemberPTSessionDatesCompletedEventHandler(object sender, GetMemberPTSessionDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMemberPTSessionDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMemberPTSessionDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateMemberPasswordAccountCompletedEventHandler(object sender, UpdateMemberPasswordAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMemberPasswordAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMemberPasswordAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public MemberPassword Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((MemberPassword)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string cPasswordNew {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitEventCompletedEventHandler(object sender, SubmitEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stEventUpdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stEventUpdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitEventRegisterCompletedEventHandler(object sender, SubmitEventRegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitEventRegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitEventRegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stEventUpdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stEventUpdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SubmitEnquiryCompletedEventHandler(object sender, SubmitEnquiryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitEnquiryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitEnquiryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public stEnquiryUpdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((stEnquiryUpdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWhatsOnCompletedEventHandler(object sender, GetWhatsOnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWhatsOnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWhatsOnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPartnersCompletedEventHandler(object sender, GetPartnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPartnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPartnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591